# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 * * * *'  # Runs every hour at minute 0

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Check if it's time to run tests
      shell: bash
      run: |
        TODAY=$(date -u +"%Y-%m-%d")
        RANDOM_SEED=$(echo -n "$TODAY" | shasum | cut -d' ' -f1)
        RANDOM_HOUR=$(( 16#${RANDOM_SEED:0:2} % 24 ))
        CURRENT_HOUR=$(date -u +"%H")
        echo "Random hour for today is $RANDOM_HOUR"
        if [ "$CURRENT_HOUR" -eq "$RANDOM_HOUR" ]; then
          echo "It's time to run the tests."
        else
          echo "Not the time to run tests yet."
          exit 0
        fi
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
